### ISSUE TITLE
Checklist for all the requirements of the template

### ISSUE THREAD

**Issue by uderbashi** [uderbashi/GTU_Thesis_LaTeX_Template#1]
This is a tracker issue to track the requirements of the template found [here](https://www.gtu.edu.tr/Files/Yonetmelik_ve_Yonergeler/Y%C3%B6netmelikler/Tez%20Yaz%C4%B1m%20K%C4%B1lavuzu%20-GT%C3%9C06012015.pdf)

This can be added to or checked if something is done.

Start the line with `- [ ]` to create the task, and if decided not to work on it use strikethrough `~~`

# 2
- [x] Thesis in Turkish (Fixed Turkish and added English as well)

## 2.2
- [X] A4 paper
- [X]  Only face up (önlü arkalı iki yüzüne basılabilir == you can not do it if you wish, thus lets skip it)
- [x] All in one font (Times new roman or Calibri) (Should we change the default font of LaTeX?)
- [X] 12pt font
- [X] 1.5 spacing 

## 2.3
- [X] margins are 4cm left, 2.5 rest

## 2.5
- [x] indentation should be 1cm
- [x] No extra space shall be left between paragraphs
- [x] margin before and after equations, tables, and figures of 18pt
- [x] the distance between the label text and the table or figure 12pt
- [x] Space after outer titles shall be 24pt
- [x] Space before and after inner titles (Main thesis) shall be 18pt, except chapter has no space before it
- [X] Chapter shall be uppercase

## 2.6
- [X] frontmatter should be using Roman numeral 
- [X] frontmatter's numbering should be centered
- [X] main matter should be using Arabic numerals
- [X] main matter should be right aligned
- [X] numbering should not have any lines or boxes (plain number)
- [x] numbering should be 11pt (have not looked into it)

## 2.7
- [x] All titles shall be bold
- [x] chapters shall be 18pt, sections 16, subsections and sub-subsection 14pt

## 2.8
- [X] referncing style (I used IEEE style of biblatex since  I found it suitable numerically, alphabetic is bullshit, since it requires vb. for Turkish papers, and et al for foreign, which I found retarded and backwards) 

## 2.9
- [x] !!?? (didn't get what they were after)

## 2.10
- [x] Footnotes shall be written in 10pt
- [x] Shall not take space from the actual footer space (the 2.5 cm)
- [x] #2
- [x] footnotes use single spacing
- [ ] between two footnotes a space of 6pt shall exist (isn't it too small? or did I misunderstand?)
- [x] the numbering of footnotes shall not carry on to the next page (if two pages have a footnote each, both of them will be numbered 1)
